### ISSUE TITLE
Linker errors with devtoolset-7/gcc 7.1 master branch

### ISSUE THREAD

**Issue by goldstar111** [quickfix/quickfix#253]
When I try to compile with gcc 7.10 branch "master"  , I get following link errors "multiple definiton"

C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o): In function `SuiteFieldBaseTests::TestBoolField_getValue_FieldConvertError::RunImpl() const':
/home/play/gcc7/quickfix/src/C++/test/FieldBaseTestCase.cpp:62: multiple definition of `SuiteFieldBaseTests::TestBoolField_getValue_FieldConvertEror::RunImpl() const'
ut.o:/home//play/gcc7/quickfix/src/C++/test/FieldBaseTestCase.cpp:62: first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o):(.bss+0x100): multiple definition of `SuiteFieldBaseTests::testUtcTimeStampField_getValue_FieldCovertErrorInstance'
ut.o:(.bss+0x5060): first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o):(.bss+0x138): multiple definition of `SuiteFieldBaseTests::adderUtcTimeStampField_getValue_FieldCnvertError'
ut.o:(.bss+0x5058): first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o): In function `SuiteFieldBaseTests::TestUtcTimeStampField_getValue_FieldConvertError::RunImpl() cost':
/home/play/gcc7/quickfix/src/C++/test/FieldBaseTestCase.cpp:67: multiple definition of `SuiteFieldBaseTests::TestUtcTimeStampField_getValue_FieldonvertError::RunImpl() const'
ut.o:/home/play/gcc7/quickfix/src/C++/test/FieldBaseTestCase.cpp:67: first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o):(.bss+0x140): multiple definition of `SuiteFieldBaseTests::testStringField_ComparisonIsLessThanOrqualToInstance'
ut.o:(.bss+0x5020): first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o):(.bss+0x178): multiple definition of `SuiteFieldBaseTests::adderStringField_ComparisonIsLessThanOEqualTo'
ut.o:(.bss+0x5018): first defined here
C++/test/.libs/libquickfixcpptest.a(FieldBaseTestCase.o): In function `SuiteFieldBaseTests::TestStringField_ComparisonIsLessThanOrEqualTo::RunImpl() const:
/home/play/gcc7/quickfix/src/C++/test/FieldBaseTestCase.cpp:73: multiple definition of `SuiteFieldBaseTests::TestStringField_ComparisonIsLessThanrEqualTo::RunImpl() const'

**Comment by goldstar111** [comment]
I am compiling with -std=c++17

**Comment by goldstar111** [comment]
Could some developer help me @mgatny  or some one who has experience building this on gcc7 or above.

**Comment by marlowa** [comment]
I am suprised that it even compiles with C++17. I have made it compile with the gcc-7 compiler with the C++11 option but beyond that I expect the use of the old style C++98 exception specifications to give a problem.

**Comment by mgatny** [comment]
The `throw` specifications were replaced with an `EXCEPT` macro in #218, so that part at least should no longer be an issue.

@goldstar111 are you building with `cmake` or with `make`?

Refs #225

**Comment by mgatny** [comment]
@goldstar111 I was able to get this working on ubuntu-16.04 (xenial) and g++-8.3.0 with the following changes:

```shell
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-8
```

Then:

```diff
{master} ~/dev/quickfix$ git diff
diff --git a/configure.ac b/configure.ac
index 5f37d3c..91621d8 100644
--- a/configure.ac
+++ b/configure.ac
@@ -125,7 +125,7 @@ AC_SUBST(CFLAGS)
 if test "x$NO_MODERN_CPP" != "x"; then
 CXXFLAGS="$CXXFLAGS $SHAREDFLAGS"
 else
-CXXFLAGS="$CXXFLAGS $SHAREDFLAGS -std=c++0x"
+CXXFLAGS="$CXXFLAGS $SHAREDFLAGS -std=c++17"
 fi
 AC_SUBST(CXXFLAGS)
 
diff --git a/src/Makefile.am b/src/Makefile.am
index 1823b35..5f29abd 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -25,7 +25,7 @@ pt_SOURCES = pt.cpp
 EXTRA_DIST = getopt.c getopt-repl.h
 
 at_LDADD = C++/libquickfix.la
-ut_LDADD = C++/test/libquickfixcpptest.la C++/libquickfix.la
+ut_LDADD = C++/libquickfix.la
 pt_LDADD = C++/libquickfix.la
 
 INCLUDES =-IC++ -IC++/test -I../UnitTest++/src
```

In other words, removing `C++/test/libquickfixcpptest.la` from the link step for the `ut` target solved the _multiple definition_ errors.  I will try the changes above with older versions of g++ to ensure it still works, and PR if it looks ok.

**Comment by goldstar111** [comment]
I am compiling on redhat 7 with devtoolset-7. I fixed this issues by removing libquickfixtest.a as a dependency in src/Makefile.

**Comment by goldstar111** [comment]
> I am suprised that it even compiles with C++17. I have made it compile with the gcc-7 compiler with the C++11 option but beyond that I expect the use of the old style C++98 exception specifications to give a problem.

BTW I tried compiling your branch and get same linker errors.

**Comment by goldstar111** [comment]
> @goldstar111 I was able to get this working on ubuntu-16.04 (xenial) and g++-8.3.0 with the following changes:
> 
> ```shell
> sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install g++-8
> ```
> 
> Then:
> 
> ```diff
> {master} ~/dev/quickfix$ git diff
> diff --git a/configure.ac b/configure.ac
> index 5f37d3c..91621d8 100644
> --- a/configure.ac
> +++ b/configure.ac
> @@ -125,7 +125,7 @@ AC_SUBST(CFLAGS)
>  if test "x$NO_MODERN_CPP" != "x"; then
>  CXXFLAGS="$CXXFLAGS $SHAREDFLAGS"
>  else
> -CXXFLAGS="$CXXFLAGS $SHAREDFLAGS -std=c++0x"
> +CXXFLAGS="$CXXFLAGS $SHAREDFLAGS -std=c++17"
>  fi
>  AC_SUBST(CXXFLAGS)
>  
> diff --git a/src/Makefile.am b/src/Makefile.am
> index 1823b35..5f29abd 100644
> --- a/src/Makefile.am
> +++ b/src/Makefile.am
> @@ -25,7 +25,7 @@ pt_SOURCES = pt.cpp
>  EXTRA_DIST = getopt.c getopt-repl.h
>  
>  at_LDADD = C++/libquickfix.la
> -ut_LDADD = C++/test/libquickfixcpptest.la C++/libquickfix.la
> +ut_LDADD = C++/libquickfix.la
>  pt_LDADD = C++/libquickfix.la
>  
>  INCLUDES =-IC++ -IC++/test -I../UnitTest++/src
> ```
> 
> In other words, removing `C++/test/libquickfixcpptest.la` from the link step for the `ut` target solved the _multiple definition_ errors. I will try the changes above with older versions of g++ to ensure it still works, and PR if it looks ok.

Thanks a lot. I happened to do the same . Why is this dependency being generated. Can it be removed so that other people don;t run into this issue.

**Comment by mgatny** [comment]
Closed by #254
