### ISSUE TITLE
C++17  g++-8.2.1 compilation failures for some calls to FieldBase& getField(FieldBase& field)

### ISSUE THREAD

**Issue by marlowa** [quickfix/quickfix#224]
The getField method is non-const but is called from const functions sometimes. This was found in quickfix 1.15.1. These calls fail to compile with g++-8.2.1. For an example, see Message.cpp, line 576 where we get the error:

Message.cpp:576:37: error: passing 'const FIX::Header' as 'this' argument discards qualifiers [-fpermissive]

**Comment by marlowa** [comment]
I found I could get it to compile by adding const to the getField methods.
