### ISSUE TITLE
C++17 g++-8.2.1 fails to link ut program

### ISSUE THREAD

**Issue by marlowa** [quickfix/quickfix#225]
With quickfix 1.15.1 adjusted so that it compiles with g++-8.2.1 I found that the program ut fails to link. It gives a couple of cases of undefined reference to vtable for FIX::TestApplication, one for the dtor and one for the default ctor.
